---
- hosts: all
  become: yes

  vars_files:
    - secret.yml
    - user_list.yml
  
  tasks:
  - name:  Removing Users
    user:
      name: "{{ item.username }}"
      uid: "{{ item.uid }}"
      state: absent
      remove: yes
    with_items: "{{ users }}"
